<?xml version="1.0" encoding="UTF-8"?>
<!-- ================================================================================ -->
<!-- ==== WSDL information											             ==== -->
<!-- ================================================================================ -->
<!--
	WSDL Filename: 		Atrias-MIG6-CMS-IsAvailable_v01-01p001.wsdl
	WSDL Version: 		v01-01p001
	WSDL Issue date:	31/05/2016
	WSDL Issued by: 	Atrias
	WSDL Description:	
		Following operations are exposed by the CMS towards the Market Parties in this WSDL:
		- IsAvailable
-->
<wsdl:definitions name="Atrias-MIG6-CMS-IsAvailable"
targetNamespace="http://www.atrias.be/msg/mig6/01-01/wsdl"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:wsdltns="http://www.atrias.be/msg/mig6/01-01/wsdl"
xmlns:msgtns="http://www.atrias.be/msg/mig6/01-01/IsAvailable"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<wsdl:types>
		<xsd:schema
		targetNamespace="http://www.atrias.be/msg/mig6/01-01/IsAvailable"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified">
			<xsd:include schemaLocation="Atrias-MIG6-CMS-IsAvailable-MsgDefinitions_v01-01p001.xsd"/>
			<xsd:element name="IsAvailable" type="msgtns:IsAvailableRequest"/>
			<xsd:element name="IsAvailableResponse" type="msgtns:IsAvailableResponse"/>
			<xsd:element name="SoapFaultDoc" type="msgtns:SoapFaultDoc"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IsAvailableRequest">
		<wsdl:part name="parameters" element="msgtns:IsAvailable"/>
	</wsdl:message>
	<wsdl:message name="IsAvailableResponse">
		<wsdl:part name="parameters" element="msgtns:IsAvailableResponse"/>
	</wsdl:message>
	<wsdl:message name="IsAvailableSoapFaultDoc">
		<wsdl:part name="parameters" element="msgtns:SoapFaultDoc"/>
	</wsdl:message>
	<wsdl:portType name="IsAvailable_PortType">
		<wsdl:operation name="IsAvailable">
			<wsdl:input message="wsdltns:IsAvailableRequest"/>
			<wsdl:output message="wsdltns:IsAvailableResponse"/>
			<wsdl:fault name="SoapFaultDoc" message="wsdltns:IsAvailableSoapFaultDoc"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="AtriasMIG6_IsAvailable_Binder" type="wsdltns:IsAvailable_PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IsAvailable">
			<soap:operation soapAction="IsAvailable" style="document"/>
			<wsdl:input>
				<soap:body parts="parameters" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="parameters" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="SoapFaultDoc">
				<soap:fault name="SoapFaultDoc" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AtriasMIG6_IsAvailable">
		<wsdl:port name="AtriasMIG6_IsAvailable_Port" binding="wsdltns:AtriasMIG6_IsAvailable_Binder">
			<soap:address location="https://server.dummyendpoint:9999/mig6/01-01/Atrias-MIG6-CMS-IsAvailable_v01-01p001"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>