import refParser from '@apidevtools/json-schema-ref-parser';
import { writeFileSync } from 'fs';
import jsonSchemaAvro from 'jsonschema-avro';
import { basename, resolve } from 'path';
import {
  CompletedConfig,
  createFormatter,
  createParser,
  createProgram,
  DEFAULT_CONFIG,
  Definition,
  ObjectType,
  ObjectTypeFormatter,
  SchemaGenerator,
} from 'ts-json-schema-generator';

function shouldIgnoreKey(key: string): boolean {
  return key === 'constructor' || key.startsWith('_');
}

// Filters out some autogenerated stuff, e.g. constructors
export class CustomFormatter extends ObjectTypeFormatter {
  protected override getObjectDefinition(type: ObjectType): Definition {
    const result = super.getObjectDefinition(type);
    if (!result.properties) {
      return result;
    }
    const filtered = {
      ...result,
      properties: Object.entries(result.properties).reduce(
        (acc, [key, value]) => (shouldIgnoreKey(key) ? acc : { ...acc, [key]: value }),
        {}
      ),
    };
    return filtered;
  }
}

const generateSchema = async (schemaFilePath: string) => {
  const config: CompletedConfig = {
    ...DEFAULT_CONFIG,
    path: schemaFilePath,
    type: 'document',
  };
  // We configure the formatter an add our custom formatter to it.
  const formatter = createFormatter(config, (fmt, circularReferenceTypeFormatter) => {
    // If your formatter DOES support children, you'll need this reference too:
    fmt.addTypeFormatter(new CustomFormatter(circularReferenceTypeFormatter));
  });
  const program = createProgram(config);
  const parser = createParser(program, config);
  const generator = new SchemaGenerator(program, parser, formatter, config);
  const schema = generator.createSchema(config.type);

  const resolvedSchema = await refParser.dereference(schema);

  const avro = jsonSchemaAvro.convert(resolvedSchema);

  // convert numbers to strings - difficult to rationalise between schema and data and
  // we can simply handle raw data as strings to prevent error anyway
  // TODO: there might be a nicer way to do this with the SchemaGenerator config
  const postProcessed = JSON.stringify(avro, null, 2).replaceAll(
    /\"double\"/g,
    '"string"'
  );

  console.log(postProcessed);
};

generateSchema(process.argv[2]);
